#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ZSHRC="$HOME/.zshrc"
ENV_VAR_NAME="NOTES_ENCRYPT_KEY"

log()  { printf '  ✓ %s\n' "$1"; }
warn() { printf '  ⚠ %s\n' "$1"; }
fail() { printf '  ✗ %s\n' "$1" >&2; exit 1; }

printf '\n=== Vault Encryption Setup ===\n\n'

# --- Dependencies -----------------------------------------------------------

if ! command -v brew &>/dev/null; then
  fail "Homebrew not found. Install it first: https://brew.sh"
fi

needs_install=()

if ! command -v openssl &>/dev/null; then
  needs_install+=(openssl)
else
  log "openssl found: $(command -v openssl)"
fi

if ! command -v gsha256sum &>/dev/null && ! command -v sha256sum &>/dev/null; then
  needs_install+=(coreutils)
else
  log "sha256 hasher found"
fi

if [[ ${#needs_install[@]} -gt 0 ]]; then
  printf '  Installing via brew: %s\n' "${needs_install[*]}"
  brew install "${needs_install[@]}"
  log "Dependencies installed"
else
  log "All dependencies present"
fi

# --- Encryption key ----------------------------------------------------------

if grep -q "export ${ENV_VAR_NAME}=" "$ZSHRC" 2>/dev/null; then
  log "Key already configured in $ZSHRC"
else
  key="$(uuidgen)"
  printf '\n# Vault encryption key (generated by scripts/setup.sh)\nexport %s="%s"\n' \
    "$ENV_VAR_NAME" "$key" >> "$ZSHRC"
  log "Generated encryption key and appended to $ZSHRC"
  warn "Run 'source ~/.zshrc' or open a new terminal to activate it"
fi

# --- Git hooks ---------------------------------------------------------------

install_hook() {
  local hook_name="$1" target_script="$2"
  local hook_path="${REPO_ROOT}/.git/hooks/${hook_name}"

  cat > "$hook_path" <<HOOK
#!/usr/bin/env bash
exec "\$(git rev-parse --show-toplevel)/scripts/${target_script}"
HOOK
  chmod +x "$hook_path"
  log "Installed .git/hooks/${hook_name}"
}

install_hook "pre-commit" "encrypt.sh"
install_hook "post-merge"  "decrypt.sh"

# --- Done --------------------------------------------------------------------

printf '\n=== Setup complete ===\n'
printf 'Next steps:\n'
printf '  1. source ~/.zshrc\n'
printf '  2. Edit .secure to list directory patterns to encrypt\n'
printf '  3. Use git as normal — encryption/decryption is automatic\n\n'
